### PR TITLE
Fix several Clang 11 warnings

### PR DESCRIPTION
**Pull request by gruenich**
Fixed multiple warnings from Clang 11, but not all. Some remove ambiguities, some are more personal coding style. The negations around strncmp are actual bugs.
If you like to merge only selected commits, I can remove the ones you do not like.

### CODE REVIEW

**Comment by gruenich** [comment]
@xiaoyeli Do you mind having a look and maybe merging?

**Review by xiaoyeli — COMMENTED** [review]
csnode_bmod.c and ccolumn_bmod.c are 2 separate routines, I don't see why the first file needs to include the 2nd one.

**Review by xiaoyeli — APPROVED** [review]

**Comment by gruenich** [comment]
Because without the include I get the following warnings:
```
[ 16%] Building C object SRC/CMakeFiles/superlu.dir/csnode_bmod.c.o
/home/gruenich/superlu/SRC/csnode_bmod.c:115:2: warning: implicit declaration of function 'clsolve' is invalid in C99 [-Wimplicit-function-declaration]
        clsolve ( nsupr, nsupc, &lusup[luptr], &lusup[ufirst] );
        ^
/home/gruenich/superlu/SRC/csnode_bmod.c:116:2: warning: implicit declaration of function 'cmatvec' is invalid in C99 [-Wimplicit-function-declaration]
        cmatvec ( nsupr, nrow, nsupc, &lusup[luptr+nsupc], 
        ^
2 warnings generated.
```
The added include fixes the warnings. Maybe I got something wrong.

Even without a better idea, I can remove this commit, if you merge the other ones.

**Review by xiaoyeli — APPROVED** [review]

**Review by xiaoyeli — APPROVED** [review]

**Review by xiaoyeli — APPROVED** [review]

**Review by xiaoyeli — APPROVED** [review]

**Review by xiaoyeli — APPROVED** [review]

**Comment by xiaoyeli** [comment]
I just cleaned up the code, removed all the warnings, and incorporated all your suggested changes. The master branch is updated.

**Comment by gruenich** [comment]
Thanks for reviewing and including the changes!

**Comment by BJWiley233** [comment]
@xiaoyeli can you indicate which changes you made in to get rid of the `warning: implicit declaration of function '<my_func>' is invalid in C99` [-Wimplicit-function-declaration]`. 

I am compiling a program that uses superlu and am getting it for `xerbla_` in sp_ienv.c:
```
../../../src/superlu/sp_ienv.c:67:5: error: implicit declaration of function 'xerbla_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    xerbla_("sp_ienv", &i);
    ^
```

**Comment by xiaoyeli** [comment]
Two points:
1) "implicit declaration" means that a proper prototype for the function is missing. In this case, xerbla_() did not have prototype in sp_ienv.c
2) It seems you are using an older version of SuperLU.  The recent version do not use xerbla anymore.

**Pull request closed without merging**
